{
 "title": "HLF SmartBFT Dashboard",
 "description": "Comprehensive monitoring dashboard for Hyperledger Fabric networks using SmartBFT consensus algorithm. Tracks view changes, transaction processing, batch metrics, and pool performance.",
 "tags": [
  "hyperledger",
  "fabric",
  "smartbft",
  "blockchain",
  "consensus",
  "distributed-systems"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(consensus_smartbft_view_decisions, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(consensus_smartbft_view_decisions{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(consensus_smartbft_view_decisions{cluster=\"$cluster\"}, channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "view decisions",
   "type": "timeseries",
   "description": "Tracks the number of view decisions made by the SmartBFT consensus.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "consensus_smartbft_view_decisions{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "batch counter  rate",
   "type": "timeseries",
   "description": "The number of transactions per batch.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_view_count_batch_all{cluster=\"$cluster\", channel=~\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transactions counter rate",
   "type": "timeseries",
   "description": "The number of transactions per batch.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_view_count_txs_all{cluster=\"$cluster\", channel=~\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transactions per batch",
   "type": "timeseries",
   "description": "The number of transactions per batch.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "consensus_smartbft_view_count_txs_in_batch{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader id",
   "type": "timeseries",
   "description": "The leader id.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "consensus_smartbft_view_leader_id{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "view number",
   "type": "timeseries",
   "description": "view number",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "consensus_smartbft_view_number{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " average batch size (rate)",
   "type": "timeseries",
   "description": "average batch size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_view_size_batch{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "view sequence number (current view)",
   "type": "timeseries",
   "description": "The sequence number within current view.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "consensus_smartbft_view_proposal_sequence{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time to process the batch (0.95 percentile)",
   "type": "timeseries",
   "description": "Amount of time it take to process batch.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(consensus_smartbft_view_latency_batch_processing_bucket{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Viewchange and sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "current view of viewchange",
   "type": "timeseries",
   "description": "current view of viewchange on this channel.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "consensus_smartbft_viewchange_current_view{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "next view of viewchange",
   "type": "timeseries",
   "description": "next view of viewchange on this channel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "consensus_smartbft_viewchange_next_view{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "real view of viewchange on this channel",
   "type": "timeseries",
   "description": "real view of viewchange on this channel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "consensus_smartbft_viewchange_real_view{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average time it takes to sync node",
   "type": "timeseries",
   "description": "An average time it takes to sync node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_consensus_latency_sync_sum{cluster=\"$cluster\", channel=~\"$channel\"})[$__rate_interval] / rate(consensus_smartbft_consensus_latency_sync_count{cluster=\"$cluster\", channel=~\"$channel\"})[$__rate_interval]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconfiguration requests (rate)",
   "type": "timeseries",
   "description": "reconfiguration requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_consensus_reconfig{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "number of elements in the consensus request pool",
   "type": "timeseries",
   "description": "Number of elements in the consensus request pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "consensus_smartbft_pool_count_of_elements{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total amount of elements in the request pool (rate)",
   "type": "timeseries",
   "description": "Total amount of elements in the request pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_pool_count_of_elements_all{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time request resides in the pool",
   "type": "timeseries",
   "description": "The average request processing time, time request resides in the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_pool_latency_of_elements_sum{cluster=\"$cluster\", channel=~\"$channel\"}) / rate(consensus_smartbft_pool_latency_of_elements_count{cluster=\"$cluster\", channel=~\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pool insertion failure (by reason)",
   "type": "timeseries",
   "description": "Number of requests pool insertion failure",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "rate(sum by (reason, instance, channel) (consensus_smartbft_pool_count_of_fail_add_request{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests forwarded to the leader (rate)",
   "type": "timeseries",
   "description": "Number of requests forwarded to the leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_pool_count_leader_forward_request{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "elements removed from the request pool (rate)",
   "type": "timeseries",
   "description": "Number of elements removed from the request pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_pool_count_of_delete_request{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests forwarded to the leader (second timeout) (rate)",
   "type": "timeseries",
   "description": "Number of times requests reached second timeout.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "rate(consensus_smartbft_pool_count_timeout_two_step{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "count of wal-files",
     "type": "timeseries",
     "description": "Count of wal-files",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 620 },
     "targets": [
      {
       "expr": "consensus_smartbft_wal_count_of_files{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Blacklist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "count of nodes in blacklist ",
     "type": "timeseries",
     "description": "Count of nodes in blacklist on this channel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 629 },
     "targets": [
      {
       "expr": "consensus_smartbft_blacklist_count{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node ID in blacklist",
     "type": "timeseries",
     "description": "Node ID in blacklist on this channel.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 629 },
     "targets": [
      {
       "expr": "consensus_smartbft_node_id_in_blacklist{instance=~\"$instance\", channel=~\"$channel\", cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}